name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Set up Conan
      shell: bash
      run: |
        pip install conan
        conan --version
        conan profile detect --force  # Detectar y crear un perfil por defecto

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install libmicrohttpd-dev
        echo "Running Conan install"
        mkdir -p build && cd build
        conan install .. --build=missing -s build_type=Release

    - name: Compile
      shell: bash
      run: |
        echo "Running CMake build"
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        make

    - name: CONFIG_MOVE
      shell: bash
      run: |
        echo "Moving configuration files"
        cp config.json build/
